title: "TEZBLOG"
welcomemsg: "Welcome To Tezblog"
description: "이것저것 기록해두는 개인 블로그"
permalink: post/:title
url: https://tezblog.github.io
tag_order: [leetcode,dev,msoffice]

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true